export default {
    page: { width: '1919px', height: '1080px' },
    box: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-start',
      flexDirection: 'row',
      justifyContent: 'center',
      backgroundColor: '#ffffff',
      width: '1919px',
      height: '1080px',
    },
    layer: { position: 'absolute', top: '0px', left: '0px', width: '1919px', height: '1080px' },
    primary: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'column',
      marginTop: '184px',
      backgroundColor: 'rgba(109,129,224,0.27)',
      width: '595px',
      height: '658px',
      overflow: 'hidden',
    },
    color: {
      position: 'relative',
      marginTop: '57px',
      backgroundColor: '#7fa5d3',
      width: '62px',
      height: '63px',
      overflow: 'hidden',
    },
    title: {
      position: 'relative',
      marginTop: '38px',
      maxWidth: '1125px',
      height: '27px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '28px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '28px',
    },
    wrap: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '113px',
      borderRadius: '28.5px',
      backgroundColor: 'rgba(26,44,104,0.70)',
      width: '432px',
      height: '57px',
      overflow: 'hidden',
    },
    icon: { marginLeft: '33px', width: '29px', height: '29px' },
    block: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '26px',
      borderRadius: '28.5px',
      backgroundColor: 'rgba(26,44,104,0.70)',
      width: '432px',
      height: '57px',
      overflow: 'hidden',
    },
    icon_2: { marginLeft: '35px', width: '25px', height: '30px' },
    group: {
      boxSizing: 'border-box',
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '94px',
      borderRadius: '28.5px',
      backgroundColor: '#1080e4',
      paddingRight: '85px',
      paddingLeft: '86px',
      height: '57px',
      overflow: 'hidden',
    },
    word: {
      textDecoration: 'none',
      lineHeight: '28px',
      letterSpacing: '0px',
      whiteSpace: 'pre',
      color: '#ffffff',
      fontSize: '28px',
    },
  };
  