export default {
  page: { width: '1920px', height: '1080px' },
  box: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    width: '1920px',
    height: '1080px',
  },
  layer: { position: 'absolute', top: '0px', left: '0px', width: '1920px', height: '1080px' },
  primary: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'column',
    width: '1920px',
    height: '1080px',
  },
  bg: { position: 'absolute', top: '0px', alignSelf: 'center', width: '1920px', height: '1080px' },
  title: {
    position: 'relative',
    marginTop: '111px',
    marginLeft: '182px',
    maxWidth: '1726px',
    height: '31px',
    overflow: 'hidden',
    textDecoration: 'none',
    textOverflow: 'ellipsis',
    lineHeight: '32px',
    letterSpacing: '0px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '32px',
  },
  block_7: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: '29px',
    width: '1565px',
    height: '240px',
  },
  group: {
    display: 'flex',
    alignItems: 'flex-start',
    flexDirection: 'column',
    marginRight: '89px',
    backgroundColor: '#2b83ed',
    width: '489px',
    height: '240px',
    overflow: 'hidden',
  },
  container: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '37px',
    width: '427px',
    height: '111px',
  },
  outer: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '103px' },
  txt: {
    position: 'relative',
    textDecoration: 'none',
    lineHeight: '78px',
    letterSpacing: '0px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '78px',
  },
  word: {
    position: 'relative',
    marginTop: '19px',
    marginLeft: '8px',
    maxWidth: '140px',
    height: '18px',
    overflow: 'hidden',
    textDecoration: 'none',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    letterSpacing: '0px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '20px',
  },
  logo: { marginTop: '10px', width: '130px', height: '101px' },
  block_2: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '8px',
    marginLeft: '38px',
    width: '384px',
    height: '52px',
  },
  block: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '52px' },
  wrap: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: '1px',
    height: '25px',
  },
  icon: { marginRight: '8px', width: '20px', height: '25px' },
  txt_2: {
    marginTop: '5px',
    textDecoration: 'none',
    lineHeight: '20px',
    letterSpacing: '0px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '20px',
  },
  text: {
    position: 'relative',
    marginTop: '9px',
    textDecoration: 'none',
    lineHeight: '20px',
    letterSpacing: '0px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '20px',
  },
  text_2: {
    marginTop: '23px',
    textDecoration: 'none',
    lineHeight: '20px',
    letterSpacing: '0px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '20px',
  },
  block_3: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '50px',
    marginRight: '99px',
    width: '118px',
    height: '150px',
  },
  group_2: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#67c163',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon: { width: '57px', height: '58px' },
  word_2: {
    position: 'relative',
    marginTop: '11px',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  group_3: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '48px',
    marginRight: '100px',
    width: '118px',
    height: '154px',
  },
  container_2: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#f5a73b',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_2: { width: '75px', height: '59px' },
  text_3: {
    position: 'relative',
    marginTop: '14px',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  block_5: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '48px',
    marginRight: '99px',
    width: '118px',
    height: '153px',
  },
  block_4: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#677beb',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_3: { width: '55px', height: '62px' },
  txt_3: {
    position: 'relative',
    marginTop: '14px',
    textAlign: 'left',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  group_5: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '48px',
    marginRight: '99px',
    width: '118px',
    height: '152px',
  },
  group_4: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#4bb9df',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_4: { width: '62px', height: '59px' },
  word_3: {
    position: 'relative',
    marginTop: '13px',
    textAlign: 'left',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  block_6: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '48px',
    width: '118px',
    height: '153px',
  },
  container_3: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#ef6d6d',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_5: { width: '61px', height: '61px' },
  text_4: {
    position: 'relative',
    marginTop: '14px',
    textAlign: 'left',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  block_13: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: '9px',
    width: '1565px',
    height: '243px',
  },
  actionBgWrap: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '89px',
    backgroundColor: '#2dccdb',
    backgroundImage: 'linear-gradient(to bottom, rgb(87,102,116), rgb(119,138,154))',
    width: '489px',
    height: '243px',
    overflow: 'hidden',
  },
  actionBg: { width: '454px', height: '221px' },
  block_9: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '57px',
    marginRight: '99px',
    width: '118px',
    height: '151px',
  },
  block_8: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#f5a73b',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_6: { marginTop: '4px', width: '59px', height: '58px' },
  txt_4: {
    position: 'relative',
    marginTop: '11px',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  group_7: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '55px',
    marginRight: '100px',
    width: '118px',
    height: '154px',
  },
  group_6: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'row',
    borderRadius: '14px',
    backgroundColor: '#87cd85',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_7: { marginTop: '32px', marginLeft: '28px', width: '70px', height: '62px' },
  word_4: {
    position: 'relative',
    marginTop: '14px',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  block_10: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '55px',
    marginRight: '99px',
    width: '118px',
    height: '153px',
  },
  container_4: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#f7a73d',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_8: { marginTop: '4px', width: '66px', height: '66px' },
  text_5: {
    position: 'relative',
    marginTop: '14px',
    textAlign: 'left',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  group_8: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '55px',
    marginRight: '99px',
    width: '118px',
    height: '153px',
  },
  block_11: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#6979e9',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_9: { width: '72px', height: '62px' },
  txt_5: {
    position: 'relative',
    marginTop: '14px',
    textAlign: 'left',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  block_12: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '55px',
    width: '118px',
    height: '153px',
  },
  group_9: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#5997cf',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_10: { width: '67px', height: '62px' },
  word_5: {
    position: 'relative',
    marginTop: '13px',
    textAlign: 'left',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  block_19: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: '9px',
    width: '1565px',
    height: '243px',
  },
  articleWrap: {
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'flex-start',
    flexDirection: 'row',
    marginRight: '89px',
    backgroundColor: '#6b6b6b',
    paddingRight: '33px',
    paddingLeft: '28px',
    height: '243px',
    overflow: 'hidden',
  },
  article: {
    WebkitLineClamp: '10px',
    marginTop: '30px',
    width: '428px',
    height: '195px',
    overflow: 'hidden',
    textDecoration: 'none',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    letterSpacing: '0px',
    color: '#ffffff',
    fontSize: '20px',
  },
  block_14: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '60px',
    marginRight: '99px',
    width: '118px',
    height: '150px',
  },
  container_5: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#49b7df',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_11: { marginTop: '-3px', width: '52px', height: '71px' },
  txt_6: {
    position: 'relative',
    marginTop: '12px',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  group_10: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '58px',
    marginRight: '100px',
    width: '118px',
    height: '153px',
  },
  block_15: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'row',
    borderRadius: '14px',
    backgroundColor: '#677beb',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  logo_2: { marginTop: '34px', marginLeft: '20px', width: '87px', height: '60px' },
  word_6: {
    position: 'relative',
    marginTop: '13px',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  block_16: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '58px',
    marginRight: '99px',
    width: '118px',
    height: '152px',
  },
  group_11: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#f36f71',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_12: { marginTop: '-3px', width: '61px', height: '61px' },
  text_6: {
    position: 'relative',
    marginTop: '14px',
    textAlign: 'left',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  group_12: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '58px',
    marginRight: '99px',
    width: '118px',
    height: '153px',
  },
  container_6: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#67c163',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_13: { width: '73px', height: '60px' },
  txt_7: {
    position: 'relative',
    marginTop: '13px',
    textAlign: 'left',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
  block_18: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: '58px',
    width: '118px',
    height: '153px',
  },
  block_17: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '14px',
    backgroundColor: '#87cd85',
    width: '118px',
    height: '118px',
    overflow: 'hidden',
  },
  largeIcon_14: { width: '58px', height: '66px' },
  word_7: {
    position: 'relative',
    marginTop: '13px',
    textDecoration: 'none',
    lineHeight: '22px',
    letterSpacing: '1.76px',
    whiteSpace: 'nowrap',
    color: '#cfcfcf',
    fontSize: '22px',
  },
};
