export default {
    page: { width: '1919px', height: '1080px' },
    box: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'column',
      backgroundColor: '#ffffff',
      width: '1919px',
      height: '1080px',
    },
    layer: { position: 'absolute', top: '0px', alignSelf: 'center', width: '1919px', height: '1080px' },
    hd: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      backgroundColor: '#2b3f9d',
      width: '1919px',
      height: '75px',
      overflow: 'hidden',
    },
    block: { display: 'flex', alignItems: 'center', flexDirection: 'row', marginRight: '587px', height: '38px' },
    color: { marginRight: '15px', backgroundColor: '#80a5d4', width: '30px', height: '30px', overflow: 'hidden' },
    title: {
      textDecoration: 'none',
      lineHeight: '40px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '40px',
    },
    view: {
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginRight: '42px',
      backgroundColor: '#0d1d73',
      width: '150px',
      height: '75px',
      overflow: 'hidden',
    },
    text: {
      maxWidth: '138px',
      height: '22px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '22px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '22px',
    },
    txt: {
      marginRight: '70px',
      textDecoration: 'none',
      lineHeight: '22px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '22px',
    },
    word: {
      marginRight: '69px',
      textDecoration: 'none',
      lineHeight: '22px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '22px',
    },
    text_2: {
      marginRight: '61px',
      textDecoration: 'none',
      lineHeight: '22px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '22px',
    },
    txt_2: {
      textDecoration: 'none',
      lineHeight: '22px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '22px',
    },
    bd: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: '20px',
      width: '1890px',
      height: '968px',
    },
    itemWrap: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-start',
      flexDirection: 'column',
      width: '470px',
      height: '968px',
    },
    block_2: {
      display: 'flex',
      position: 'absolute',
      bottom: '0px',
      alignItems: 'center',
      alignSelf: 'center',
      flexDirection: 'row',
      backgroundColor: '#23358d',
      width: '469px',
      height: '408px',
      overflow: 'hidden',
    },
    word_2: {
      position: 'absolute',
      top: '15px',
      left: '17px',
      textDecoration: 'none',
      lineHeight: '20px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#18fff7',
      fontSize: '20px',
    },
    block_3: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'column',
      marginLeft: '1px',
      backgroundColor: '#23358d',
      width: '469px',
      height: '215px',
      overflow: 'hidden',
    },
    group: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: '15px',
      width: '440px',
      height: '26px',
    },
    txt_3: {
      marginTop: '-4px',
      maxWidth: '321px',
      height: '20px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '20px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#18fff7',
      fontSize: '20px',
    },
    infoWrap: {
      boxSizing: 'border-box',
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'row',
      backgroundColor: '#152987',
      paddingRight: '12px',
      paddingLeft: '13px',
      height: '26px',
      overflow: 'hidden',
    },
    info: {
      textDecoration: 'none',
      lineHeight: '14px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#a2aee7',
      fontSize: '14px',
    },
    article: {
      WebkitLineClamp: '4px',
      position: 'relative',
      marginTop: '25px',
      width: '440px',
      height: '119px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '30px',
      letterSpacing: '0px',
      color: '#fefeff',
      fontSize: '16px',
    },
    block_8: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-start',
      flexDirection: 'column',
      marginTop: '20px',
      marginLeft: '1px',
      backgroundColor: '#23358d',
      width: '469px',
      height: '305px',
      overflow: 'hidden',
    },
    block_5: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      alignSelf: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: '12px',
      width: '440px',
      height: '26px',
    },
    word_3: {
      maxWidth: '321px',
      height: '20px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '20px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#18fff7',
      fontSize: '20px',
    },
    block_4: {
      boxSizing: 'border-box',
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'row',
      backgroundColor: '#152987',
      paddingRight: '19px',
      paddingLeft: '13px',
      height: '26px',
      overflow: 'hidden',
    },
    text_3: {
      textDecoration: 'none',
      lineHeight: '14px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#a2aee7',
      fontSize: '14px',
    },
    group_2: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      alignSelf: 'center',
      flexDirection: 'row',
      marginTop: '39px',
      width: '406px',
      height: '17px',
    },
    text_4: {
      marginTop: '-4px',
      marginRight: '56px',
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    txt_4: {
      marginTop: '-4px',
      marginRight: '67px',
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    hpaPrev: {
      marginTop: '-4px',
      marginRight: '53px',
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    hpa: {
      marginTop: '-4px',
      marginRight: '30px',
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    ppm: {
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    block_7: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: '10px',
      marginLeft: '40px',
      width: '407px',
      height: '38px',
    },
    group_3: {
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginRight: '42px',
      width: '40px',
      height: '37px',
    },
    icon: { marginTop: '6px', marginRight: '8px', width: '20px', height: '31px' },
    icon_2: { width: '12px', height: '35px', overflow: 'hidden' },
    container: {
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginRight: '34px',
      width: '57px',
      height: '37px',
    },
    icon_3: { marginTop: '6px', marginRight: '8px', width: '37px', height: '31px' },
    icon_4: { width: '12px', height: '35px', overflow: 'hidden' },
    block_6: {
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginRight: '38px',
      width: '56px',
      height: '37px',
    },
    icon_5: { marginTop: '4px', marginRight: '11px', width: '33px', height: '33px' },
    icon_6: { width: '12px', height: '35px', overflow: 'hidden' },
    group_4: {
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: '-3px',
      marginRight: '39px',
      width: '46px',
      height: '35px',
    },
    icon_7: { marginTop: '5px', marginRight: '6px', width: '28px', height: '30px' },
    icon_8: { width: '12px', height: '35px', overflow: 'hidden' },
    container_2: {
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      width: '55px',
      height: '35px',
    },
    icon_9: { marginRight: '11px', width: '32px', height: '34px' },
    icon_10: { width: '12px', height: '35px', overflow: 'hidden' },
    group_5: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      alignSelf: 'center',
      flexDirection: 'row',
      marginTop: '9px',
      width: '390px',
      height: '15px',
    },
    word_4: {
      marginRight: '57px',
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    text_5: {
      marginRight: '60px',
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    txt_5: {
      marginRight: '58px',
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    word_5: {
      marginRight: '58px',
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    text_6: {
      textAlign: 'center',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    colorDiv: {
      position: 'relative',
      alignSelf: 'center',
      marginTop: '23px',
      backgroundColor: '#12268c',
      width: '442px',
      height: '94px',
      overflow: 'hidden',
    },
    item: { position: 'relative', marginTop: '20px', width: '470px', height: '408px' },
    view_2: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '968px' },
    floorBgWrap: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      backgroundColor: '#2b3f9d',
      width: '908px',
      height: '156px',
      overflow: 'hidden',
    },
    floorBg: { width: '899px', height: '149px' },
    bgWrap: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-start',
      flexDirection: 'row',
      marginTop: '20px',
      backgroundColor: '#23358d',
      width: '908px',
      height: '510px',
      overflow: 'hidden',
    },
    bg: { position: 'absolute', top: '0px', left: '0px', width: '908px', height: '510px' },
    productLong: { position: 'absolute', top: '20px', left: '159px', width: '249px', height: '462px' },
    productWrap: {
      display: 'flex',
      position: 'absolute',
      bottom: '30px',
      left: '165px',
      alignItems: 'center',
      flexDirection: 'row',
      width: '249px',
      height: '218px',
    },
    product: { position: 'relative', width: '249px', height: '218px' },
    txt_6: {
      position: 'absolute',
      top: '104px',
      left: '86px',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    itemLongWrap: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '18px',
      marginRight: '45px',
      marginLeft: '180px',
      width: '232px',
      height: '327px',
    },
    itemLong: { position: 'relative', width: '232px', height: '327px' },
    word_6: {
      position: 'absolute',
      top: '129px',
      left: '82px',
      textDecoration: 'none',
      lineHeight: '20px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '20px',
    },
    text_7: {
      position: 'absolute',
      top: '79px',
      left: '64px',
      textDecoration: 'none',
      lineHeight: '16px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '16px',
    },
    block_10: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-end',
      flexDirection: 'column',
      marginTop: '50px',
      width: '406px',
      height: '423px',
    },
    block_9: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-start',
      flexDirection: 'column',
      backgroundColor: 'rgba(3,11,47,0.50)',
      width: '194px',
      height: '92px',
      overflow: 'hidden',
    },
    infoWrap_2: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '16px',
      marginLeft: '26px',
      height: '23px',
    },
    icon_11: { marginRight: '11px', width: '24px', height: '23px' },
    info_2: {
      textDecoration: 'none',
      lineHeight: '18px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '18px',
    },
    num: {
      position: 'relative',
      alignSelf: 'center',
      marginTop: '15px',
      maxWidth: '144px',
      height: '23px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '30px',
      letterSpacing: '1.5px',
      whiteSpace: 'nowrap',
      color: '#ffcd01',
      fontSize: '30px',
    },
    group_6: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-start',
      flexDirection: 'column',
      marginTop: '16px',
      backgroundColor: 'rgba(3,11,47,0.50)',
      width: '194px',
      height: '92px',
      overflow: 'hidden',
    },
    outer: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '15px',
      marginLeft: '26px',
      height: '22px',
    },
    icon_12: { marginRight: '11px', width: '24px', height: '22px' },
    txt_7: {
      textDecoration: 'none',
      lineHeight: '18px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '18px',
    },
    percent: {
      position: 'relative',
      alignSelf: 'center',
      marginTop: '17px',
      maxWidth: '118px',
      height: '23px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '30px',
      letterSpacing: '1.5px',
      whiteSpace: 'nowrap',
      color: '#ed6647',
      fontSize: '30px',
    },
    container_3: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-start',
      flexDirection: 'column',
      marginTop: '18px',
      backgroundColor: 'rgba(3,11,47,0.50)',
      width: '405px',
      height: '205px',
      overflow: 'hidden',
    },
    infoWrap_3: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '16px',
      marginLeft: '14px',
      height: '21px',
    },
    icon_13: { marginRight: '11px', width: '24px', height: '21px' },
    info_3: {
      textDecoration: 'none',
      lineHeight: '18px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '18px',
    },
    entryPicWrap: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: '9px',
      marginLeft: '26px',
      width: '361px',
      height: '141px',
    },
    wrap: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', marginTop: '-6px', height: '55px' },
    text_8: {
      position: 'relative',
      marginLeft: '23px',
      maxWidth: '40px',
      height: '17px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '18px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '18px',
    },
    num_2: {
      position: 'relative',
      marginTop: '15px',
      textDecoration: 'none',
      lineHeight: '30px',
      letterSpacing: '1.5px',
      whiteSpace: 'nowrap',
      color: '#30fcdc',
      fontSize: '30px',
    },
    entryPic: { width: '251px', height: '141px' },
    block_13: {
      display: 'flex',
      position: 'relative',
      alignItems: 'flex-end',
      flexDirection: 'row',
      marginTop: '20px',
      backgroundColor: '#2b3f9d',
      width: '908px',
      height: '262px',
      overflow: 'hidden',
    },
    group_7: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '241px' },
    info_4: {
      position: 'relative',
      marginLeft: '18px',
      maxWidth: '617px',
      height: '19px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '20px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#18fff7',
      fontSize: '20px',
    },
    banner: { position: 'relative', width: '647px', height: '222px' },
    block_12: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '262px' },
    block_11: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      backgroundColor: '#23358d',
      width: '261px',
      height: '79px',
      overflow: 'hidden',
    },
    icon_14: { marginRight: '11px', marginLeft: '25px', width: '23px', height: '21px' },
    info_5: {
      maxWidth: '202px',
      height: '18px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '18px',
      letterSpacing: '2.88px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '18px',
    },
    group_8: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '13px',
      backgroundColor: '#23358d',
      width: '261px',
      height: '79px',
      overflow: 'hidden',
    },
    icon_15: { marginTop: '5px', marginRight: '13px', marginLeft: '25px', width: '21px', height: '20px' },
    info_6: {
      maxWidth: '202px',
      height: '17px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '18px',
      letterSpacing: '2.88px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '18px',
    },
    container_4: {
      display: 'flex',
      position: 'relative',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: '12px',
      backgroundColor: '#23358d',
      width: '261px',
      height: '79px',
      overflow: 'hidden',
    },
    icon_16: { marginTop: '6px', marginRight: '15px', marginLeft: '23px', width: '21px', height: '21px' },
    info_7: {
      marginTop: '5px',
      maxWidth: '202px',
      height: '18px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '18px',
      letterSpacing: '2.88px',
      whiteSpace: 'nowrap',
      color: '#ffffff',
      fontSize: '18px',
    },
    descWrap: {
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'column',
      backgroundColor: '#23358d',
      width: '468px',
      height: '968px',
      overflow: 'hidden',
    },
    desc: {
      position: 'relative',
      marginTop: '13px',
      maxWidth: '280px',
      height: '23px',
      overflow: 'hidden',
      textDecoration: 'none',
      textOverflow: 'ellipsis',
      lineHeight: '24px',
      letterSpacing: '0px',
      whiteSpace: 'nowrap',
      color: '#18fff7',
      fontSize: '24px',
    },
    itemLong_2: { position: 'relative', marginTop: '15px', width: '468px', height: '917px' },
  };
  